Add

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -1,14 +1,14 @@
 # This is a basic workflow to help you get started with Actions
 
-name: CI
+name: Terraform Plan
 
 # Controls when the workflow will run
 on:
   # Triggers the workflow on push or pull request events but only for the "main" branch
-  push:
-    branches: [ "master" ]
-  pull_request:
-    branches: [ "master" ]
+  #push:
+  #  branches: [ "main" ]
+  #pull_request:
+  #  branches: [ "main" ]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -26,7 +26,7 @@ on:
 # A workflow run is made up of one or more jobs that can run sequentially or in parallel
 jobs:
   # This workflow contains a single job called "build"
-  build:
+  plan:
     # The type of runner that the job will run on
     runs-on: ubuntu-latest
 
@@ -39,6 +39,19 @@ jobs:
       - name: Run a one-line script
         run: echo Hello, world!
 
+      - name: Print working directory
+        run: pwd
+
+      - name: List files in working directory
+        run: ls -al
+
+      - name: Set up AWS CLI
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ap-south-1  # Specify your region
+      
       # Runs a set of commands using the runners shell
       - name: Run a multi-line script
         run: |
@@ -47,14 +60,65 @@ jobs:
         
       - name: Set up Terraform
         uses: hashicorp/setup-terraform@v2
-        with:
-          terraform_version: 1.5.0 # Specify your Terraform version
+        #with:
+        #  terraform_version: 1.9.5
 
+      
+          
       - name: Terraform Init
         working-directory: ${{ github.workspace }}
-        run: terraform init
-
+        run: |
+          cd DEV && rm -rf .terraform  && terraform init -upgrade
       - name: Terraform Plan
-        id: terraform-plan
         working-directory: ${{ github.workspace }}
-        run: terraform plan -var-file="DEV/dev-terraform.tfvars"
+        run: |
+          # Define the path to the tfvars file
+          tfvars_file="${{ github.event.inputs.environment }}-terraform.tfvars"
+          
+          # Check if the tfvars file exists
+          #if [ ! -f "$tfvars_file" ]; then
+          #  echo "Error: File $tfvars_file does not exist."
+          #  exit 1
+          #fi
+          
+          # Run terraform plan with the specified tfvars file
+          #terraform plan -var-file="$tfvars_file"
+          
+          cd DEV && rm -rf tfplan && terraform plan -var-file="$tfvars_file" -out=tfplan
+      - name: Upload Terraform Plan
+        uses: actions/upload-artifact@v3
+        with:
+          name: terraform-plan
+          path: ${{ github.workspace }}
+
+  apply:
+    needs: plan
+    runs-on: ubuntu-latest
+    environment:
+      name: ${{ github.event.inputs.environment }}  # Reference the environment
+
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+
+      - name: Set up AWS CLI
+        uses: aws-actions/configure-aws-credentials@v2
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
+
+      - name: Set up Terraform
+        uses: hashicorp/setup-terraform@v2
+        #with:
+        #  terraform_version: 1.9.5
+
+      - name: Download Terraform Plan
+        uses: actions/download-artifact@v3
+        with:
+          name: terraform-plan
+          path: ${{ github.workspace }} 
+
+      - name: Terraform Apply
+        working-directory: ${{ github.workspace }}
+        run: cd DEV && terraform apply -auto-approve tfplan
